# -*- mode:org; mode:visual-line; coding:utf-8; -*-
VobSub2SRT is a simple command line program to convert =.idx= / =.sub= subtitles into =.srt= text subtitles by using OCR. It is based on code from the [[http://www.mplayerhq.hu][MPlayer project]] - a really really great movie player. [[http://code.google.com/p/tesseract-ocr/][Tesseract]] is used as OCR software.

vobsub2srt is released under the GPL3+ license. The mplayer code included is GPL2+ licensed.

Currently the OCR results are more or less useless. But this should improve with correct preprocessing.

* Building
You need tesseract and libavutil (part of the [[http://ffmpeg.org/][FFmpeg]] project). You also need cmake and a gcc to build it. With Ubuntu 10.04 you can install the dependencies with

#+BEGIN_EXAMPLE
  sudo apt-get install libavutil-dev tesseract-ocr-dev tesseract-ocr-eng build-essential cmake
#+END_EXAMPLE

You should also install the tesseract data for the languages you want to use!

#+BEGIN_EXAMPLE
  ./configure
  make
  sudo make install
#+END_EXAMPLE

This should install the program vobsub2srt to =/usr/local/bin=. You can uninstall vobsub2srt with =sudo make uninstall=.

* Usage
vobsub2srt converts subtitles in VobSub (=.idx= / =.sub=) format into subtitles in =.srt= format. VobSub subtitles consist of two or three files called =Filename.idx=, =Filename.sub= and optional =Filename.ifo=. To convert subtitles simply call

#+BEGIN_EXAMPLE
  vobsub2srt Filename
#+END_EXAMPLE

with =Filename= being the filename of the subtitle files *WITHOUT* the extension (=.idx= / =.sub=). vobsub2srt writes the subtitles to a file called =Filename.srt=.

If a subtitle file contains more than one language you can use the =--lang= parameter to set the correct language (Use =--verbose= to find out about the languages in the file).

If you want to dump the subtitles as images (e.g. to check for correct ocr) you can use the =--dump-images= flag.

* To Do
- implement preprocessing (first step scaling. Code available in =spudec.c=)
