# -*- mode:org; mode:visual-line; coding:utf-8; -*-
VobSub2SRT is a simple command line program to convert =.idx= / =.sub= subtitles into =.srt= text subtitles by using OCR. It is based on code from the [[http://www.mplayerhq.hu][MPlayer project]] - a really really great movie player. [[http://code.google.com/p/tesseract-ocr/][Tesseract]] is used as OCR software.

vobsub2srt is released under the GPL3+ license. The MPlayer code included is GPL2+ licensed.

The quality of the OCR depends on the text in the subtitles. Currently the code does not use any preprocessing. But I'm currently looking into adding filters and scaling options to improve the OCR. You can correct mistakes in the =.srt= files with a text editor or a special subtitle editor.

* Building
You need tesseract and libavutil (part of the [[http://ffmpeg.org/][FFmpeg]] project). You also need cmake and a gcc to build it. With Ubuntu 10.04 you can install the dependencies with

#+BEGIN_EXAMPLE
  sudo apt-get install libavutil-dev libtiff4-dev tesseract-ocr-dev tesseract-ocr-eng build-essential cmake
#+END_EXAMPLE

You should also install the tesseract data for the languages you want to use!

#+BEGIN_EXAMPLE
  ./configure
  make
  sudo make install
#+END_EXAMPLE

This should install the program vobsub2srt to =/usr/local/bin=. You can uninstall vobsub2srt with =sudo make uninstall=. You can build a *.deb package (Debian/Ubuntu) with =make package=. The package is created in the =build= directory. Vobsub2srt contains a formula for [[http://mxcl.github.com/homebrew/][Homebrew]] (a package manager for OS X). It can be installed by using the command =brew install https://github.com/ruediger/VobSub2SRT/raw/master/vobsub2srt.rb=.

* Usage
vobsub2srt converts subtitles in VobSub (=.idx= / =.sub=) format into subtitles in =.srt= format. VobSub subtitles consist of two or three files called =Filename.idx=, =Filename.sub= and optional =Filename.ifo=. To convert subtitles simply call

#+BEGIN_EXAMPLE
  vobsub2srt Filename
#+END_EXAMPLE

with =Filename= being the file name of the subtitle files *WITHOUT* the extension (=.idx= / =.sub=). vobsub2srt writes the subtitles to a file called =Filename.srt=.

If a subtitle file contains more than one language you can use the =--lang= parameter to set the correct language (Use =--verbose= to find out about the languages in the file).

If you want to dump the subtitles as images (e.g. to check for correct ocr) you can use the =--dump-images= flag.

Use =--help= or read the manpage to get more information about the options of vobsub2srt.

* Contributors
Most code is from the MPlayer project.
- Armin Häberling <armin.aha@gmail.com> wrote a patch to fix an issue with multiple instances of the same subtitle in result file (21af426)
- James Harris <jimmy@jamesharris.org> wrote the formula for Homebrew (54f311d6)
- Leo Koppelkamm reported and fixed issue #5 and problems with long filenames (b903074c, 36ec8da, d3602d6)

* To Do
- implement preprocessing (first step scaling. Code available in =spudec.c=)
